import type { StaticItem } from "./content.js";

export const bashExpansionItems: StaticItem[] = [
  {
    id: "bash-expansion-quoted-argv",
    kind: "bash",
    topic: "Bash",
    prompt: "value='alpha beta'; printf '<%s>\\n' $value \"$value\"\n\nWhat exact lines does printf emit? Each <...> is one argument.",
    answer: "Exact stdout is <alpha>\\n<beta>\\n<alpha beta>\\n. The unquoted $value undergoes word splitting and supplies two arguments. The quoted \"$value\" preserves alpha beta as one argument. Pathname expansion would follow splitting, but neither resulting word is a pattern here.",
    choices: [
      "<alpha>\\n<beta>\\n<alpha beta>\\n",
      "<alpha beta>\\n<alpha beta>\\n",
      "<alpha>\\n<beta>\\n<alpha>\\n<beta>\\n",
      "<$value>\\n<$value>\\n",
    ],
    correctChoice: "<alpha>\\n<beta>\\n<alpha beta>\\n",
    source: { label: "GNU Bash manual, Word Splitting", url: "https://www.gnu.org/software/bash/manual/html_node/Word-Splitting.html" },
  },
  {
    id: "bash-expansion-brace-before-parameter",
    kind: "bash",
    topic: "Bash",
    prompt: "prefix=Q; printf '<%s>\\n' {$prefix,tail}\n\nWhat exact lines are emitted?",
    answer: "Exact stdout is <Q>\\n<tail>\\n. Brace expansion runs first and produces the two words $prefix and tail. Parameter expansion then changes $prefix to Q. Brace expansion is textual and does not wait for the parameter value before finding its alternatives.",
    choices: [
      "<Q>\\n<tail>\\n",
      "<$prefix>\\n<tail>\\n",
      "<{Q,tail}>\\n",
      "<Q,tail>\\n",
    ],
    correctChoice: "<Q>\\n<tail>\\n",
    source: { label: "GNU Bash manual, Brace Expansion", url: "https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html" },
  },
  {
    id: "bash-expansion-tilde-contexts",
    kind: "bash",
    topic: "Bash",
    prompt: "HOME=/tmp/quiz-home; printf '<%s>\\n' ~ \"~\" x~ PATH=~/bin\n\nWhat exact lines are emitted by Bash?",
    answer: "Exact stdout is </tmp/quiz-home>\\n<~>\\n<x~>\\n<PATH=/tmp/quiz-home/bin>\\n. An unquoted tilde expands at the start of a word and Bash also checks for one immediately after = in assignment-like words. A quoted tilde stays literal, and x~ leaves the mid-word tilde literal.",
    choices: [
      "</tmp/quiz-home>\\n<~>\\n<x~>\\n<PATH=/tmp/quiz-home/bin>\\n",
      "</tmp/quiz-home>\\n</tmp/quiz-home>\\n<x/tmp/quiz-home>\\n<PATH=/tmp/quiz-home/bin>\\n",
      "</tmp/quiz-home>\\n<~>\\n<x~>\\n<PATH=~/bin>\\n",
      "<~>\\n<~>\\n<x~>\\n<PATH=~/bin>\\n",
    ],
    correctChoice: "</tmp/quiz-home>\\n<~>\\n<x~>\\n<PATH=/tmp/quiz-home/bin>\\n",
    source: { label: "GNU Bash manual, Tilde Expansion", url: "https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html" },
  },
  {
    id: "bash-expansion-command-substitution-newlines",
    kind: "bash",
    topic: "Bash",
    prompt: "value=$(printf 'alpha\\n\\n'); printf '<%s>\\n' \"$value\"\n\nThe inner printf emits alpha plus two newline bytes. What does the outer printf emit?",
    answer: "Exact stdout is <alpha>\\n. Command substitution removes all trailing newline characters from the captured output, not just one. The double quotes then keep the remaining alpha as one argument.",
    choices: ["<alpha>\\n", "<alpha\\n>\\n", "<alpha\\n\\n>\\n", "<>\\n"],
    correctChoice: "<alpha>\\n",
    source: { label: "GNU Bash manual, Command Substitution", url: "https://www.gnu.org/software/bash/manual/html_node/Command-Substitution.html" },
  },
  {
    id: "bash-expansion-splitting-before-pathname",
    kind: "bash",
    topic: "Bash",
    prompt: "Directory: blue.log, red.log, note.txt. Locale: C.\n\npatterns='*.log note.txt'; printf '<%s>\\n' $patterns\n\nWhat exact lines are emitted?",
    answer: "Exact stdout is <blue.log>\\n<red.log>\\n<note.txt>\\n. Word splitting first turns the unquoted value into two words: *.log and note.txt. Pathname expansion then expands the first word to the two sorted .log matches; the second word already names note.txt.",
    choices: [
      "<blue.log>\\n<red.log>\\n<note.txt>\\n",
      "<*.log>\\n<note.txt>\\n",
      "<*.log note.txt>\\n",
      "<note.txt>\\n<blue.log>\\n<red.log>\\n",
    ],
    correctChoice: "<blue.log>\\n<red.log>\\n<note.txt>\\n",
    source: { label: "GNU Bash manual, Shell Expansions", url: "https://www.gnu.org/software/bash/manual/html_node/Shell-Expansions.html" },
  },
  {
    id: "bash-expansion-matched-unmatched-patterns",
    kind: "bash",
    topic: "Bash",
    prompt: "Directory: a.txt, b.txt, with no .md files. Default Bash behavior: nullglob and failglob are off.\n\nprintf '<%s>\\n' *.txt *.md\n\nWhat exact lines are emitted?",
    answer: "Exact stdout is <a.txt>\\n<b.txt>\\n<*.md>\\n. Under default Bash behavior, *.txt has matches and expands to their sorted names. *.md has no matches, so Bash leaves that pattern unchanged. nullglob would remove it, while failglob would make expansion fail; neither option is enabled here.",
    choices: [
      "<a.txt>\\n<b.txt>\\n<*.md>\\n",
      "<a.txt>\\n<b.txt>\\n",
      "<*.txt>\\n<*.md>\\n",
      "Bash reports an unmatched-pattern error",
    ],
    correctChoice: "<a.txt>\\n<b.txt>\\n<*.md>\\n",
    source: { label: "GNU Bash manual, Filename Expansion", url: "https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html" },
  },
];
