import type { CommandConcept } from "./command-content.js";

const kubectlReferences = {
  apiConcepts: { label: "Kubernetes API concepts", url: "https://kubernetes.io/docs/reference/using-api/api-concepts/" },
  apiResources: { label: "kubectl api-resources", url: "https://kubernetes.io/docs/reference/kubectl/generated/kubectl_api-resources/" },
  explain: { label: "kubectl explain", url: "https://kubernetes.io/docs/reference/kubectl/generated/kubectl_explain/" },
  get: { label: "kubectl get", url: "https://kubernetes.io/docs/reference/kubectl/generated/kubectl_get/" },
  describe: { label: "kubectl describe", url: "https://kubernetes.io/docs/reference/kubectl/generated/kubectl_describe/" },
  jsonpath: { label: "kubectl JSONPath", url: "https://kubernetes.io/docs/reference/kubectl/jsonpath/" },
  logs: { label: "kubectl logs", url: "https://kubernetes.io/docs/reference/kubectl/generated/kubectl_logs/" },
  events: { label: "kubectl events", url: "https://kubernetes.io/docs/reference/kubectl/generated/kubectl_events/" },
  service: { label: "Kubernetes Services", url: "https://kubernetes.io/docs/concepts/services-networking/service/" },
  fieldSelectors: { label: "Field selectors", url: "https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/" },
  labels: { label: "Labels and selectors", url: "https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/" },
  podLifecycle: { label: "Pod lifecycle", url: "https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/" },
  deployments: { label: "Deployments", url: "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/" },
  rolloutStatus: { label: "kubectl rollout status", url: "https://kubernetes.io/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_status/" },
  authCanI: { label: "kubectl auth can-i", url: "https://kubernetes.io/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_can-i/" },
  declarative: { label: "Declarative object management", url: "https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/" },
  diff: { label: "kubectl diff", url: "https://kubernetes.io/docs/reference/kubectl/generated/kubectl_diff/" },
  serverSideApply: { label: "Server-Side Apply", url: "https://kubernetes.io/docs/reference/using-api/server-side-apply/" },
  crdVersioning: { label: "CRD versioning", url: "https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/" },
};

const platform = "kubectl 1.35+ against a GitOps-owned cluster";

export const kubectlConcepts: CommandConcept[] = [
  {
    command: "kubectl",
    concept: "request-scope",
    label: "resource identity, --context, -n, and -A",
    platform,
    references: [kubectlReferences.apiConcepts, kubectlReferences.get],
    definition: {
      prompt: "What identifies a Kubernetes API object, and how should one kubectl request make cluster and namespace scope explicit?",
      answer: "Within a namespace, object identity is the tuple of API group, resource, namespace, and name. Different served versions of one group and resource represent the same underlying object. Namespaced resources need namespace scope, while cluster-scoped resources such as Nodes do not. kubectl uses the current context and that context's namespace unless overridden. For a sensitive inspection, prefer explicit --context and -n/--namespace for one command instead of mutating global context state; -A/--all-namespaces intentionally lists a namespaced resource across every namespace.\n\nMemory hook: type + cluster + namespace + name before flags.",
    },
    read: {
      prompt: "Assume another terminal may have changed your defaults.\n\nCommand:\nkubectl --context homelab get deployments.apps quiz -n quiz\n\nWhat object and scope does this request select?",
      choices: [
        "Deployment quiz in namespace quiz on context homelab",
        "Every Deployment named quiz in every namespace on the current context",
        "Cluster-scoped Deployment quiz on context homelab",
        "The current namespace is changed permanently to quiz",
      ],
      correctChoice: "Deployment quiz in namespace quiz on context homelab",
      answer: "It selects the apps API Deployment named quiz, in namespace quiz, using context homelab. The explicit flags affect this command only; they do not rewrite kubeconfig defaults.",
    },
    write: {
      prompt: "Inspect Service quiz in namespace quiz on context homelab without changing persistent context defaults. Which command is safest and complete?",
      choices: [
        "kubectl --context homelab get service quiz -n quiz",
        "kubectl get service quiz",
        "kubectl config set-context --current --namespace=quiz && kubectl get service quiz",
        "kubectl --context homelab get service quiz -A",
      ],
      correctChoice: "kubectl --context homelab get service quiz -n quiz",
      answer: "kubectl --context homelab get service quiz -n quiz makes both cluster and namespace scope explicit for this request without changing persistent defaults.",
    },
  },
  {
    command: "kubectl",
    concept: "api-discovery",
    label: "api-resources, api-versions, and raw discovery",
    platform,
    references: [kubectlReferences.apiResources, kubectlReferences.apiConcepts],
    definition: {
      prompt: "How do you discover which resource types and API versions this API server serves?",
      answer: "kubectl api-resources reports served resource names, API group/version, namespaced scope, Kind, short names, and, with -o wide, supported verbs. kubectl api-versions lists served group/versions. kubectl get --raw /api/v1 reads core-resource discovery, while /apis/apps/v1 reads one named API group/version. A fully qualified resource such as applications.argoproj.io avoids short-name or group ambiguity. These discovery interfaces identify served types, not their field schema and not the instances currently stored.\n\nMemory hook: resources and versions first, schema second, objects third.",
    },
    read: {
      prompt: "Discovery row:\nNAME          SHORTNAMES   APIVERSION             NAMESPACED   KIND\napplications  app,apps     argoproj.io/v1alpha1   true         Application\n\nWhat can you conclude?",
      choices: [
        "Application is a namespaced resource served at argoproj.io/v1alpha1; applications.argoproj.io is an unambiguous resource name",
        "Application is cluster-scoped and stored only as v1alpha1 in etcd",
        "One Application instance named applications currently exists",
        "Application is a built-in core/v1 type",
      ],
      correctChoice: "Application is a namespaced resource served at argoproj.io/v1alpha1; applications.argoproj.io is an unambiguous resource name",
      answer: "The row describes a served API resource type and its scope. It does not prove that any Application instances exist or reveal the storage encoding/version.",
    },
    write: {
      prompt: "Inspect the resource names, versions, scope, Kinds, and verbs served for the longhorn.io API group. Which command fits?",
      choices: [
        "kubectl api-resources --api-group=longhorn.io -o wide",
        "kubectl get longhorn.io -A -o wide",
        "kubectl api-versions --api-group=longhorn.io -o wide",
        "kubectl explain longhorn.io --recursive",
      ],
      correctChoice: "kubectl api-resources --api-group=longhorn.io -o wide",
      answer: "kubectl api-resources --api-group=longhorn.io -o wide filters discovery to that API group and includes the wider columns, including verbs.",
    },
  },
  {
    command: "kubectl",
    concept: "schema-introspection",
    label: "explain, OpenAPI, and CRD schemas",
    platform,
    references: [kubectlReferences.explain, kubectlReferences.crdVersioning],
    definition: {
      prompt: "Which interfaces answer what fields define a resource type?",
      answer: "kubectl explain reads the server's OpenAPI schema. Append nested fields such as pods.spec.containers, choose a served version with --api-version, or use --recursive for a one-level-deeper field inventory. kubectl get --raw /openapi/v3 exposes the OpenAPI discovery index. Built-in types are not CRDs; their schemas come from Kubernetes OpenAPI and API reference docs. For a custom resource, the CustomResourceDefinition is the defining API object, and each spec.versions entry carries an openAPIV3Schema; inspect it with kubectl get customresourcedefinition NAME -o yaml when authorized.\n\nMemory hook: explain the schema, get an object instance.",
    },
    read: {
      prompt: "Command:\nkubectl explain pods.status.containerStatuses.restartCount --api-version=v1\n\nOutput begins:\nFIELD: restartCount <integer>\n\nWhat did this establish?",
      choices: [
        "restartCount is an integer field in the served v1 Pod schema",
        "Every current Pod has restarted at least once",
        "restartCount is an etcd revision number",
        "Pods are defined by a CustomResourceDefinition",
      ],
      correctChoice: "restartCount is an integer field in the served v1 Pod schema",
      answer: "kubectl explain established schema shape and documentation for the served v1 Pod API. It did not retrieve a Pod instance or its current restart count.",
    },
    write: {
      prompt: "Inspect the Longhorn Volume schema field numberOfReplicas at the explicitly served longhorn.io/v1beta2 version. Which command fits?",
      choices: [
        "kubectl explain volume.spec.numberOfReplicas --api-version=longhorn.io/v1beta2",
        "kubectl get volume.spec.numberOfReplicas --api-version=longhorn.io/v1beta2",
        "kubectl api-resources volume.spec.numberOfReplicas -o yaml",
        "kubectl explain persistentvolume.spec.numberOfReplicas",
      ],
      correctChoice: "kubectl explain volume.spec.numberOfReplicas --api-version=longhorn.io/v1beta2",
      answer: "kubectl explain volume.spec.numberOfReplicas --api-version=longhorn.io/v1beta2 asks the server schema for that nested custom-resource field without reading an instance.",
    },
  },
  {
    command: "kubectl",
    concept: "object-inspection",
    label: "get, describe, wide, JSONPath, and custom columns",
    platform,
    references: [kubectlReferences.get, kubectlReferences.describe, kubectlReferences.jsonpath],
    definition: {
      prompt: "When should you use kubectl get, describe, and explicit output formats?",
      answer: "kubectl get retrieves a list or one named object and is the normal starting point. -o wide adds common operational columns; -o YAML or JSON exposes the API representation of current instances. JSONPath extracts fields, and custom-columns builds a compact table. Single-quote JSONPath and custom-column expressions in the shell so braces, wildcards, and spaces reach kubectl unchanged. kubectl describe renders a human-oriented diagnostic summary with related objects and, for one object by default, events; it is not a stable machine-readable schema.\n\nMemory hook: get to find and shape, describe to investigate one object.",
    },
    read: {
      prompt: "Fixture Pod quiz-abc has ready=true, restartCount=0, and nodeName=talos-worker-05.\n\nCommand:\nkubectl get pod quiz-abc -n quiz -o custom-columns='NAME:.metadata.name,READY:.status.containerStatuses[*].ready,RESTARTS:.status.containerStatuses[*].restartCount,NODE:.spec.nodeName'\n\nWhich data row is printed?",
      choices: [
        "quiz-abc   true   0   talos-worker-05",
        "quiz-abc   Running   quiz   apps/v1",
        "true   talos-worker-05   quiz-abc   1",
        "A full YAML Pod document",
      ],
      correctChoice: "quiz-abc   true   0   talos-worker-05",
      answer: "custom-columns prints the selected fields in declared column order. The shell quotes preserve the expression, and [*] selects every container-status value.",
    },
    write: {
      prompt: "Print only the configured container image values from Deployment quiz in namespace quiz. Which command uses a shell-safe JSONPath?",
      choices: [
        "kubectl get deployment quiz -n quiz -o jsonpath='{.spec.template.spec.containers[*].image}'",
        "kubectl describe deployment quiz -n quiz -o jsonpath=.image",
        "kubectl get deployment -A -o wide quiz.image",
        "kubectl explain deployment.spec.template.spec.containers.image -n quiz",
      ],
      correctChoice: "kubectl get deployment quiz -n quiz -o jsonpath='{.spec.template.spec.containers[*].image}'",
      answer: "The JSONPath follows the Deployment's Pod template to every container image, and single quotes keep the template intact in the shell.",
    },
  },
  {
    command: "kubectl",
    concept: "selectors",
    label: "-l labels and --field-selector",
    platform,
    references: [kubectlReferences.labels, kubectlReferences.fieldSelectors, kubectlReferences.get],
    definition: {
      prompt: "How do label selectors and field selectors narrow kubectl get?",
      answer: "-l/--selector filters by object labels, the API's normal grouping mechanism; --show-labels reveals labels in table output. --field-selector asks the server to filter by supported object fields, but support is deliberately limited and varies by resource type. Pods support fields such as status.phase and spec.nodeName, while every type supports metadata.name and metadata.namespace. Comma-separated selector requirements are ANDed, so all requirements must match.\n\nMemory hook: labels group by intent, fields filter supported object state.",
    },
    read: {
      prompt: "Fixture:\nquiz-a  labels app=quiz,tier=web   phase=Running\nquiz-b  labels app=quiz,tier=web   phase=Pending\napi-a   labels app=api,tier=web    phase=Running\n\nCommand:\nkubectl get pods -n quiz -l 'app=quiz,tier=web' --field-selector=status.phase=Running\n\nWhich Pods match?",
      choices: ["quiz-a only", "quiz-a and quiz-b", "quiz-a and api-a", "All three Pods"],
      correctChoice: "quiz-a only",
      answer: "quiz-a satisfies both label requirements and the supported status.phase field requirement. Every comma-separated requirement must match.",
    },
    write: {
      prompt: "List only Running Pods labeled app=quiz in namespace quiz. Which command makes both filters explicit?",
      choices: [
        "kubectl get pods -n quiz -l app=quiz --field-selector=status.phase=Running",
        "kubectl get pods -n quiz --show-labels=status.phase=Running",
        "kubectl get pods -A -l status.phase=Running,app=quiz",
        "kubectl describe pods app=quiz status.phase=Running",
      ],
      correctChoice: "kubectl get pods -n quiz -l app=quiz --field-selector=status.phase=Running",
      answer: "-l selects the app label, while --field-selector uses the Pod field status.phase. Namespace remains explicit.",
    },
  },
  {
    command: "kubectl",
    concept: "pod-status",
    label: "phase, readiness, state, and restarts",
    platform,
    references: [kubectlReferences.podLifecycle, kubectlReferences.describe],
    definition: {
      prompt: "Which Pod fields distinguish scheduling phase from usable container health?",
      answer: "status.phase is a coarse Pod lifecycle summary such as Pending, Running, Succeeded, Failed, or Unknown; Running does not imply application readiness. status.conditions includes the Pod Ready condition. status.containerStatuses gives each container's ready flag, restartCount, current state, and lastState, which expose waiting reasons and prior termination details. metadata.ownerReferences identifies the immediate controller, often a ReplicaSet rather than the top-level Deployment.\n\nMemory hook: phase says where the Pod is, container status says whether it works.",
    },
    read: {
      prompt: "Pod fixture:\nphase: Running\nReady condition: False\ncontainer ready: false\nrestartCount: 4\nstate.waiting.reason: CrashLoopBackOff\nlastState.terminated.reason: OOMKilled\n\nWhat is the strongest conclusion?",
      choices: [
        "The Pod is Running but not Ready; its container previously OOMKilled and is now in CrashLoopBackOff after repeated restarts",
        "The workload is healthy because phase is Running",
        "The Pod is Pending because the container is not Ready",
        "The Deployment must have zero desired replicas",
      ],
      correctChoice: "The Pod is Running but not Ready; its container previously OOMKilled and is now in CrashLoopBackOff after repeated restarts",
      answer: "Running only means the Pod is bound to a node and at least one container is running, starting, or restarting. The container and last-state fields provide the discriminating failure evidence.",
    },
    write: {
      prompt: "A named Pod is Running but 0/1 Ready and restarting. Which next command gives a focused human-readable view of container state, readiness, owner, and related events?",
      choices: [
        "kubectl describe pod quiz-abc -n quiz",
        "kubectl get pods -A",
        "kubectl explain pod.status.phase",
        "kubectl rollout restart deployment quiz -n quiz",
      ],
      correctChoice: "kubectl describe pod quiz-abc -n quiz",
      answer: "kubectl describe pod quiz-abc -n quiz gathers the named Pod's status details and related events before any mutation is considered.",
    },
  },
  {
    command: "kubectl",
    concept: "logs",
    label: "container, previous, time window, and stream",
    platform,
    references: [kubectlReferences.logs],
    definition: {
      prompt: "How do you choose the exact log source instead of dumping arbitrary workload logs?",
      answer: "Start with a named Pod. Use -c CONTAINER when it has multiple containers, or --all-containers when combined output is deliberate. --previous reads the logs from the previous terminated container instance in that Pod, which is essential for a restarting container. Bound evidence with --since or --tail, use -f only when you need to follow new output, and add --prefix when interleaving multiple containers or Pods. Controller or label targets can aggregate logs, but a named Pod and container are more discriminating during diagnosis.\n\nMemory hook: pod, container, instance, time window, then follow.",
    },
    read: {
      prompt: "Pod quiz-abc has containers app and metrics. app restarted recently.\n\nCommand:\nkubectl logs pod/quiz-abc -n quiz -c app --previous --since=10m\n\nWhich source is requested?",
      choices: [
        "The previous app container instance, only entries newer than 10 minutes before the request",
        "The current app and metrics containers, followed live for 10 minutes",
        "Every previous Pod owned by the Deployment",
        "Kubernetes events from the last 10 minutes",
      ],
      correctChoice: "The previous app container instance, only entries newer than 10 minutes before the request",
      answer: "-c app selects one container, --previous switches from its current instance to its previous terminated instance, and --since=10m returns only entries newer than ten minutes before the request. It may return no lines if that instance stopped earlier.",
    },
    write: {
      prompt: "For initial triage of named Pod quiz-abc, print existing logs from every container and identify each line's source. Which command fits?",
      choices: [
        "kubectl logs pod/quiz-abc -n quiz --all-containers --prefix",
        "kubectl logs deployment/quiz -n quiz -f",
        "kubectl describe pod quiz-abc -n quiz --all-containers",
        "kubectl get pod quiz-abc -n quiz -o logs",
      ],
      correctChoice: "kubectl logs pod/quiz-abc -n quiz --all-containers --prefix",
      answer: "--all-containers intentionally includes every container in the named Pod, while --prefix keeps interleaved lines attributable.",
    },
  },
  {
    command: "kubectl",
    concept: "events",
    label: "focused Warning events and watches",
    platform,
    references: [kubectlReferences.events, kubectlReferences.describe],
    definition: {
      prompt: "What do Kubernetes Events contribute to diagnosis, and what do they not provide?",
      answer: "A namespaced Event records an observation with fields such as type, reason, message, and a regarding reference to the involved object. kubectl describe often includes related recent events; kubectl events can focus an exact object with --for, narrow to Warning or Normal with --types, and --watch for subsequent events. Events are best-effort data with limited retention, not a durable audit log, and --for one Pod does not imply all events for its owners.\n\nMemory hook: events explain controller observations, logs explain process output.",
    },
    read: {
      prompt: "Warning event for Pod quiz-abc:\nREASON: FailedScheduling\nMESSAGE: 0/4 nodes are available: 2 Insufficient memory, 2 node(s) had untolerated taint.\n\nWhat should this evidence make you inspect next?",
      choices: [
        "The scheduler constraints, especially Pod resource requests and node taints/tolerations",
        "Only the application's previous container logs",
        "The Service's targetPort because scheduling happens after routing",
        "The Deployment rollout history because it proves an image pull failure",
      ],
      correctChoice: "The scheduler constraints, especially Pod resource requests and node taints/tolerations",
      answer: "The scheduler already supplied two concrete exclusion reasons. Inspect the Pod requests and placement constraints plus matching node taints before broadening the search.",
    },
    write: {
      prompt: "Show current Warning events specifically regarding Pod quiz-abc in namespace quiz, without starting a watch. Which command fits?",
      choices: [
        "kubectl events -n quiz --for pod/quiz-abc --types=Warning",
        "kubectl get events -A --field-selector=type=Warning",
        "kubectl logs pod/quiz-abc -n quiz --previous",
        "kubectl events -n quiz --for deployment/quiz --watch",
      ],
      correctChoice: "kubectl events -n quiz --for pod/quiz-abc --types=Warning",
      answer: "--for targets that exact involved object, --types narrows the event type, and omitting --watch returns the current retained set.",
    },
  },
  {
    command: "kubectl",
    concept: "service-routing",
    label: "Service selector, ports, and EndpointSlices",
    platform,
    references: [kubectlReferences.service, kubectlReferences.get],
    definition: {
      prompt: "How do you trace a selector-based Service to the Pods that can receive traffic?",
      answer: "A Service selector must match Pod labels. The EndpointSlice objects labeled kubernetes.io/service-name=NAME show the actual backends and their readiness conditions. In a Service port entry, port is the Service port clients use, while targetPort is the destination Pod port or named container port. A healthy Deployment does not guarantee Service endpoints: labels can disagree, Pods can be unready, or targetPort can be wrong after endpoints exist.\n\nMemory hook: selector chooses Pods, EndpointSlice proves backends, targetPort reaches the process.",
    },
    read: {
      prompt: "Fixture:\nService quiz selector: app=quiz\nReady Pod quiz-abc label: app=quiz-v2\nEndpointSlice for quiz: endpoints: []\n\nWhat is the first broken link?",
      choices: [
        "The Service selector app=quiz does not match the Pod label app=quiz-v2, so there are no endpoints",
        "The Deployment is unhealthy because every Service requires two Pods",
        "targetPort is necessarily wrong because the EndpointSlice is empty",
        "The Pod must be cluster-scoped",
      ],
      correctChoice: "The Service selector app=quiz does not match the Pod label app=quiz-v2, so there are no endpoints",
      answer: "The observed mismatch fully explains the empty backend set. targetPort becomes relevant only after matching endpoints exist and traffic reaches the wrong port.",
    },
    write: {
      prompt: "Inspect the actual EndpointSlice backends associated with Service quiz in namespace quiz. Which command uses the controller-applied association label?",
      choices: [
        "kubectl get endpointslices -n quiz -l kubernetes.io/service-name=quiz -o yaml",
        "kubectl get pods -n quiz -l service=quiz -o wide",
        "kubectl describe service quiz -A --show-endpoints",
        "kubectl get service quiz -n quiz -o endpoint",
      ],
      correctChoice: "kubectl get endpointslices -n quiz -l kubernetes.io/service-name=quiz -o yaml",
      answer: "EndpointSlices for a Service carry kubernetes.io/service-name. YAML exposes each endpoint's addresses and readiness conditions plus the Slice ports without guessing Pod labels.",
    },
  },
  {
    command: "kubectl",
    concept: "workload-rollouts",
    label: "Deployment ownership, conditions, and rollout status",
    platform,
    references: [kubectlReferences.deployments, kubectlReferences.rolloutStatus],
    definition: {
      prompt: "How do you decide whether a Deployment rollout is complete or stalled?",
      answer: "A Deployment owns ReplicaSets, and ReplicaSets own Pods; metadata.ownerReferences reveals each immediate link. Compare desired replicas with updated, ready, and available replicas, then read Deployment conditions and reasons rather than trusting one READY column. kubectl rollout status watches the latest rollout until completion by default; a finite --timeout makes automation stop, and failure or timeout returns non-zero. rollout history explains revisions, while restart and undo mutate desired state and should not replace diagnosis, especially for GitOps-owned workloads.\n\nMemory hook: controller counts, conditions, new ReplicaSet, then its Pods.",
    },
    read: {
      prompt: "Deployment quiz fixture:\ndesired=2 updated=2 ready=1 available=1\nProgressing=False reason=ProgressDeadlineExceeded\nAvailable=False reason=MinimumReplicasUnavailable\n\nWhat should you conclude and inspect?",
      choices: [
        "ProgressDeadlineExceeded means the rollout is stalled; inspect the new ReplicaSet and its unready Pods",
        "The rollout succeeded because every desired Pod was updated",
        "The Service selector must be wrong because available is 1",
        "Immediately run rollout restart to clear the conditions",
      ],
      correctChoice: "ProgressDeadlineExceeded means the rollout is stalled; inspect the new ReplicaSet and its unready Pods",
      answer: "updated=desired only says the new template was used. The availability counts and explicit ProgressDeadlineExceeded condition show that the rollout did not become healthy.",
    },
    write: {
      prompt: "Wait at most 90 seconds for Deployment quiz in namespace quiz to finish its current rollout and get a useful exit status. Which command fits?",
      choices: [
        "kubectl rollout status deployment/quiz -n quiz --timeout=90s",
        "kubectl get deployment quiz -n quiz -w --timeout=90s",
        "kubectl rollout history deployment/quiz -n quiz --revision=90",
        "kubectl wait pod/quiz -n quiz --for=rollout --timeout=90s",
      ],
      correctChoice: "kubectl rollout status deployment/quiz -n quiz --timeout=90s",
      answer: "rollout status understands Deployment completion semantics, watches the current rollout, and returns non-zero on failure or timeout.",
    },
  },
  {
    command: "kubectl",
    concept: "authorization",
    label: "auth can-i, subresources, and impersonation",
    platform,
    references: [kubectlReferences.authCanI],
    definition: {
      prompt: "How do you test whether an identity may perform one exact Kubernetes API action?",
      answer: "kubectl auth can-i checks an API verb against a resource, namespace, optional object name, and optional subresource. Use API verbs such as get, list, watch, create, update, patch, and delete, not the shell command name. pods/log is a different authorization target from pods, so --subresource=log matters. --as and --as-group ask about another identity, but the caller needs impersonation permission to make that check. --list summarizes allowed actions in a scope; -q suppresses text and leaves an exit status for scripts.\n\nMemory hook: identity + verb + group/resource + subresource + scope.",
    },
    read: {
      prompt: "Results in namespace quiz:\nkubectl auth can-i get pods       -> yes\nkubectl auth can-i get pods --subresource=log -> no\n\nWhat do these results mean?",
      choices: [
        "The identity can read Pod objects but cannot read Pod logs",
        "The identity cannot read Pod objects because logs are part of every get",
        "The identity can read current logs but not previous logs",
        "The identity can list Pods in every namespace",
      ],
      correctChoice: "The identity can read Pod objects but cannot read Pod logs",
      answer: "RBAC can authorize a parent resource and its subresource differently. These checks say nothing about list permission or other namespaces.",
    },
    write: {
      prompt: "If your current identity may impersonate it, check whether ServiceAccount quiz/reader can list Pods in namespace quiz. Which command fits?",
      choices: [
        "kubectl auth can-i list pods --as=system:serviceaccount:quiz:reader -n quiz",
        "kubectl auth can-i get serviceaccount/reader --subresource=pods -n quiz",
        "kubectl get pods -n quiz --as=quiz:reader --dry-run=server",
        "kubectl auth can-i list pods -A --as-group=quiz:reader",
      ],
      correctChoice: "kubectl auth can-i list pods --as=system:serviceaccount:quiz:reader -n quiz",
      answer: "ServiceAccount usernames use system:serviceaccount:NAMESPACE:NAME, and -n scopes the list authorization check to quiz.",
    },
  },
  {
    command: "kubectl",
    concept: "apply-preview",
    label: "client dry-run, server dry-run, and diff",
    platform,
    references: [kubectlReferences.declarative, kubectlReferences.diff],
    definition: {
      prompt: "How do you preview a manifest through progressively more realistic checks without persisting it?",
      answer: "--dry-run=client performs local generation and basic client processing without contacting the API server. apply --dry-run=server sends the request through authorization, defaulting, admission, and validation but does not persist it; -o yaml reveals the resulting object. kubectl diff compares the would-be server-side configuration with live state: exit 0 means no differences, exit 1 means differences, and greater than 1 means an error. In a GitOps-owned cluster, preview from the repository, then commit and let the controller reconcile rather than using live apply as a parallel source of truth.\n\nMemory hook: render locally, validate on server, diff live, commit through the owner.",
    },
    read: {
      prompt: "Command:\nkubectl diff -f rendered.yaml\n\nIt prints a Deployment image change and exits 1. What does that exit status mean?",
      choices: [
        "Exit 1 means differences were found, not a command failure",
        "Exit 1 means the manifest was applied but the rollout failed",
        "Exit 1 means there were no differences",
        "Exit 1 always means authorization was denied",
      ],
      correctChoice: "Exit 1 means differences were found, not a command failure",
      answer: "kubectl diff deliberately uses exit 1 for a non-empty diff. Scripts must distinguish that expected result from values greater than 1, which indicate an error.",
    },
    write: {
      prompt: "Send rendered.yaml through server authorization, admission, defaulting, and validation without persisting it, then print the admitted form. Which command fits?",
      choices: [
        "kubectl apply --dry-run=server -f rendered.yaml -o yaml",
        "kubectl apply --dry-run=client -f rendered.yaml -o yaml",
        "kubectl diff --dry-run=server -f rendered.yaml -o yaml",
        "kubectl apply -f rendered.yaml && kubectl get -f rendered.yaml -o yaml",
      ],
      correctChoice: "kubectl apply --dry-run=server -f rendered.yaml -o yaml",
      answer: "Server dry-run exercises server behavior but does not persist the object. The YAML output includes server defaults and admission changes.",
    },
  },
  {
    command: "kubectl",
    concept: "apply-ownership",
    label: "server-side apply and managed fields",
    platform,
    references: [kubectlReferences.serverSideApply, kubectlReferences.declarative],
    definition: {
      prompt: "What does an apply conflict tell you about declarative ownership?",
      answer: "Server-Side Apply records field ownership in metadata.managedFields under a named field manager. When a manager tries to change a field owned by another manager, the server reports a conflict instead of silently stealing it. --force-conflicts takes ownership and overwrites the conflicting value, so it is not a casual retry flag. Traditional client-side apply instead computes its patch using the kubectl.kubernetes.io/last-applied-configuration annotation. Pick one established owner and workflow; in GitOps, change the Git source rather than fighting its controller.\n\nMemory hook: a conflict names the ownership boundary, not an obstacle to bulldoze.",
    },
    read: {
      prompt: "Server-Side Apply reports a conflict on .spec.replicas. managedFields shows manager argocd-controller owns that field. The Deployment is GitOps-managed. What is the correct response?",
      choices: [
        "Argo CD owns spec.replicas, so change the value in its Git source and let the controller reconcile",
        "Retry with --force-conflicts so kubectl permanently becomes the owner",
        "Delete managedFields from the live object",
        "Use client-side apply because it cannot conflict with controllers",
      ],
      correctChoice: "Argo CD owns spec.replicas, so change the value in its Git source and let the controller reconcile",
      answer: "The conflict is useful evidence of the declared ownership boundary. A forced live takeover would create competing sources of truth and likely be reverted.",
    },
    write: {
      prompt: "Outside GitOps, a release process intentionally owns deployment.yaml with Server-Side Apply. Which command gives that manager a stable explicit name?",
      choices: [
        "kubectl apply --server-side --field-manager=quiz-release -f deployment.yaml",
        "kubectl apply --force-conflicts -f deployment.yaml",
        "kubectl replace --field-manager=quiz-release -f deployment.yaml",
        "kubectl patch deployment.yaml --server-side=quiz-release",
      ],
      correctChoice: "kubectl apply --server-side --field-manager=quiz-release -f deployment.yaml",
      answer: "--server-side selects Server-Side Apply, and --field-manager records the stable owner identity in managedFields. Force is absent unless an ownership transfer was explicitly decided.",
    },
  },
  {
    command: "kubectl",
    concept: "api-evolution",
    label: "served, storage, conversion, and deprecation",
    platform,
    references: [kubectlReferences.crdVersioning, kubectlReferences.apiConcepts],
    definition: {
      prompt: "How do served and storage versions differ for one custom-resource API?",
      answer: "For a CRD version, served=true means the API server accepts requests at that group/version; storage=true selects the version used for newly persisted objects, and exactly one version must be marked for storage. Conversion translates multiple served representations of the same underlying custom resource. An object's apiVersion shows the representation returned or submitted, but does not prove its current storage encoding. kubectl talks to the API server, not directly to etcd, so responses can reflect defaulting, admission, and conversion rather than raw stored bytes. metadata.resourceVersion carries API concurrency and watch state, not a user-facing or cluster-global etcd revision; pass it unmodified back to the server. For Kubernetes 1.35+, numeric resource versions are orderable only for the same API group and resource, as arbitrary-size decimal integers. Outside that documented comparison, treat the token as opaque. Direct etcdctl inspection is exceptional control-plane, forensics, or disaster recovery work, not normal resource discovery. Before relying on a version, inspect server discovery and the CRD's version flags, schema, conversion strategy, and deprecation warnings.\n\nMemory hook: served is an API doorway, storage is the persisted shape.",
    },
    read: {
      prompt: "CRD versions:\n- name: v1alpha1, served: true, storage: false\n- name: v1beta1, served: true, storage: true\n\nWhat does this establish?",
      choices: [
        "v1alpha1 and v1beta1 are served, while v1beta1 is the storage version for newly persisted objects",
        "Only v1beta1 requests are accepted because storage implies served exclusivity",
        "Every existing object has already been rewritten from v1alpha1 to v1beta1",
        "v1alpha1 and v1beta1 are different resource identities with different names",
      ],
      correctChoice: "v1alpha1 and v1beta1 are served, while v1beta1 is the storage version for newly persisted objects",
      answer: "Both API doorways accept requests. v1beta1 is selected for new storage writes, but these flags alone do not prove that old stored data has been migrated or rewritten.",
    },
    write: {
      prompt: "Print each declared version of CRD widgets.example.io with its served and storage flags. Which command iterates the version entries?",
      choices: [
        "kubectl get crd widgets.example.io -o jsonpath='{range .spec.versions[*]}{.name}{\" served=\"}{.served}{\" storage=\"}{.storage}{\"\\n\"}{end}'",
        "kubectl api-versions widgets.example.io --show-storage",
        "kubectl explain widgets.example.io.spec.versions --recursive",
        "kubectl get widgets.example.io -A -o wide",
      ],
      correctChoice: "kubectl get crd widgets.example.io -o jsonpath='{range .spec.versions[*]}{.name}{\" served=\"}{.served}{\" storage=\"}{.storage}{\"\\n\"}{end}'",
      answer: "The range walks every CRD version entry and prints its name plus both flags. It inspects the API definition, not custom-resource instances.",
    },
  },
];
