import type { StaticItem } from "./content.js";

const accessedAt = "accessed 2026-10-05";
const vrRevisitedReference = {
  label: `Liskov and Cowling, Viewstamped Replication Revisited, MIT-CSAIL-TR-2012-021 (2012), ${accessedAt}`,
  url: "https://hdl.handle.net/1721.1/71763",
};
const originalVrReference = {
  label: `Oki and Liskov, Viewstamped Replication: A New Primary Copy Method (1988), ${accessedAt}`,
  url: "https://doi.org/10.1145/62546.62549",
};
const raftReference = {
  label: `Ongaro and Ousterhout, In Search of an Understandable Consensus Algorithm (2014), ${accessedAt}`,
  url: "https://raft.github.io/raft.pdf",
};

export const viewstampedReplicationItems: StaticItem[] = [
  {
    id: "vr-state-and-primary",
    kind: "command",
    topic: "Viewstamped Replication",
    prompt: "2012 VR Revisited. Fixed group: 3 replicas; crash failures only; f = 1; quorum = 2. Primaries rotate in configuration order starting with R1 in view 0.\n\nReplica R2 reports: view 4; status = normal; op-number = 7; commit-number = 6; log entries = 1..7. Configuration order: R1, R2, R3.\n\nWhich interpretation is valid?",
    choices: [
      "R2 is primary; entries 1..6 are committed, while entry 7 is present but not yet committed",
      "R1 is primary because the lowest-numbered replica is always primary; all seven entries are committed",
      "R2 is a backup; op-number 7 means entry 7 has already executed everywhere",
      "R3 is primary; status normal means R2 has no log entries awaiting commitment",
    ],
    correctChoice: "R2 is primary; entries 1..6 are committed, while entry 7 is present but not yet committed",
    answer: "In this 2012 VR variant, view 0 uses R1 and primaries rotate round-robin, so view 4 uses R2. status = normal means R2 participates in ordinary request processing. op-number 7 identifies its latest log entry; commit-number 6 says only the prefix through entry 6 is known committed. Entry 7 is present/prepared locally but not thereby committed. This uses VR's native view-number, primary, op-number, and commit-number vocabulary.",
    references: [vrRevisitedReference, originalVrReference],
  },
  {
    id: "vr-normal-operation-sequence",
    kind: "ordering",
    topic: "Viewstamped Replication",
    prompt: "Put one successful normal-operation request in protocol order. Fixed group: 3 replicas; crash failures only; f = 1; quorum = 2. Assume the request is new, replicas begin in normal status in one view, and no messages are lost.",
    orderedItems: [
      "Client sends REQUEST(operation, client-id, request-number) to the primary",
      "Primary checks the client table, appends the request with a new op-number, then sends PREPARE",
      "A backup accepts the next matching entry, appends it, and replies PREPAREOK",
      "After f PREPAREOK replies, the primary commits, executes, updates its client table, and replies",
      "A backup learns the commit-number from a later PREPARE or COMMIT, then executes the committed prefix",
    ],
    answer: "The primary orders the request first. A PREPARE makes the operation prepared at a backup, but a backup does not execute from PREPARE alone. The primary commits after PREPAREOK replies from f backups: the primary plus f backups form the f + 1 quorum. The primary then executes and replies. Backups learn the advanced commit-number through later PREPARE traffic or an explicit COMMIT heartbeat and execute committed operations in order.",
    references: [vrRevisitedReference],
  },
  {
    id: "vr-normal-quorum-commit",
    kind: "command",
    topic: "Viewstamped Replication",
    prompt: "Normal operation, one view: 5 replicas P, B1, B2, B3, B4; crash failures only; f = 2; quorum = 3. P has appended op-number 14 and sent PREPARE to every backup. B1's PREPAREOK arrives. Later B2's PREPAREOK arrives. When may P commit operation 14?",
    choices: [
      "Commit after B2's PREPAREOK: P, B1, and B2 form the three-replica quorum",
      "Commit after B1's PREPAREOK because P and one backup are a majority",
      "Wait for PREPAREOK from all four backups because every replica must prepare before commitment",
      "Commit immediately after appending because the primary's log alone defines the committed order",
    ],
    correctChoice: "Commit after B2's PREPAREOK: P, B1, and B2 form the three-replica quorum",
    answer: "With f = 2, one PREPAREOK is not enough: P plus B1 accounts for only two replicas. Two PREPAREOK replies let the primary count itself with B1 and B2, making three replicas, the f + 1 quorum. P may then consider operation 14 committed, execute it after earlier committed operations, update the client table, and reply. It need not wait for all five replicas.",
    references: [vrRevisitedReference],
  },
  {
    id: "vr-prepare-vs-commit-propagation",
    kind: "command",
    topic: "Viewstamped Replication",
    prompt: "Normal operation, 3 replicas, f = 1. Backup B1 has op-number = 9 and commit-number = 8: entry 9 arrived in PREPARE and B1 returned PREPAREOK, but it has not seen a newer commit-number. Now B1 receives the next PREPARE for op-number 10 carrying commit-number 9. What does B1 do?",
    choices: [
      "B1 advances the committed prefix through operation 9 and executes it in order; it also appends operation 10 and replies PREPAREOK",
      "B1 executes both operations 9 and 10 immediately because receiving PREPARE commits its entry",
      "B1 discards operation 9 because only the primary may retain an uncommitted entry",
      "B1 rejects operation 10 because commit-number must equal the PREPARE's op-number",
    ],
    correctChoice: "B1 advances the committed prefix through operation 9 and executes it in order; it also appends operation 10 and replies PREPAREOK",
    answer: "Before this message, entry 9 was prepared at B1 but not yet known committed there: op-number was 9 while commit-number was 8. The PREPARE carries commit-number 9, so B1 advances its committed prefix and executes operation 9 in log order. B1 also appends the next consecutive entry and replies PREPAREOK. The protocol does not require operation 9's execution before appending or acknowledging operation 10, so that local interleaving is not part of the graded outcome. Entry 10 is prepared, not committed merely by that PREPARE.",
    references: [vrRevisitedReference],
  },
  {
    id: "vr-duplicate-client-request",
    kind: "command",
    topic: "Viewstamped Replication",
    prompt: "Client C sent request-number 12. The operation committed and executed, but the reply was lost before C received it. After a view change, C retransmits request 12 to the new primary. Its replicated client table says C's latest request-number is 12 and stores the cached result. What should happen?",
    choices: [
      "Return the cached result for request 12 without appending or executing another operation",
      "Append request 12 again because a new view resets every client's request numbering",
      "Reject request 12 as stale without replying, forcing the client to skip to request 13",
      "Execute request 12 again but suppress the second reply so the log remains deterministic",
    ],
    correctChoice: "Return the cached result for request 12 without appending or executing another operation",
    answer: "A request-number equal to the client's latest number in the client table is a duplicate, so the primary resends the cached result. It does not append or execute the operation again, preserving an exactly-once effect despite retransmission. A smaller request-number is discarded as old; a larger request-number is treated as the next new request. Replicating the client table with service state lets this rule survive a view change.",
    references: [vrRevisitedReference],
  },
  {
    id: "vr-view-change-log-selection",
    kind: "command",
    topic: "Viewstamped Replication",
    prompt: "View change to view 9 in a 5-replica group, f = 2. The new primary receives a quorum of three DOVIEWCHANGE messages. Each reports (latest normal view, op-number, commit-number):\nA = (7, 12, 9), log A1..A12\nB = (8, 10, 10), log B1..B10\nC = (8, 11, 8), log C1..C11\n\nWhich log and commit-number go into STARTVIEW?",
    choices: [
      "Choose C's log through op 11, and start the new view with commit-number 10",
      "Choose A's log through op 12 because the longest log always wins, and use commit-number 9",
      "Choose B's log through op 10 because it reports the highest commit-number, and use commit-number 10",
      "Concatenate all three suffixes and use the smallest commit-number so no replica executes too far",
    ],
    correctChoice: "Choose C's log through op 11, and start the new view with commit-number 10",
    answer: "First choose among DOVIEWCHANGE logs by the largest latest-normal-view, here 8, which eliminates A even though A is longer. Break the B/C tie using the largest op-number, so C's log through 11 wins. The largest commit-number in the quorum is 10 from B; determine that independently of which log wins. STARTVIEW carries C's selected log and commit-number 10.",
    references: [vrRevisitedReference],
  },
  {
    id: "vr-view-change-committed-prefix",
    kind: "command",
    topic: "Viewstamped Replication",
    prompt: "Three replicas P, R2, R3; f = 1. In view 2, operation 6 was prepared at P and R2, then P committed and replied. P becomes unreachable. The view-change quorum is R2 and R3; R2's log contains operation 6 while R3's ends at operation 5. What must the next view do?",
    choices: [
      "Operation 6 must remain in the new view because R2 carries it into the view-change quorum",
      "Discard operation 6 because the old primary is absent from the view-change quorum",
      "Let R2 execute operation 6 but omit it from the new primary's log",
      "Choose R3's shorter log because it contains only operations known by every surviving replica",
    ],
    correctChoice: "Operation 6 must remain in the new view because R2 carries it into the view-change quorum",
    answer: "The operation-6 commit quorum {P, R2} and the view-change quorum {R2, R3} intersect at R2. R2 carries the operation prepared in the later view into the change. VR's latest normal view, then longest log selection preserves it in the new log; the protocol cannot discard an operation that may already be committed and returned to a client. Requiring intersecting f + 1 quorums is the safety bridge between views.",
    references: [vrRevisitedReference],
  },
  {
    id: "vr-partition-safety-liveness",
    kind: "command",
    topic: "Viewstamped Replication",
    prompt: "Fixed group: 5 replicas, crash failures only, f = 2, quorum = 3. A network partition leaves the old primary able to reach only itself and one backup: 2 replicas total. The other 3 replicas can communicate with one another. What follows?",
    choices: [
      "The two-replica side cannot commit; the three-replica side can form a later view and progress when communication stabilizes",
      "Both sides may commit independently because each side contains at least one backup",
      "The old primary's two-replica side may commit, while the three-replica side must wait for it",
      "Neither side can ever progress again because VR requires all five replicas after any partition",
    ],
    correctChoice: "The two-replica side cannot commit; the three-replica side can form a later view and progress when communication stabilizes",
    answer: "Safety holds on both sides because only a group of f + 1 = 3 replicas can commit normal operations or complete a view change; the old primary's two-replica side cannot do either. The three-replica side can install a later view and regain liveness during a stable period in which its protocol messages, retried repeatedly when necessary, are delivered. Asynchrony means a timeout suspects the primary; it does not prove a crash, so transient partitions can trigger extra view changes without permitting split-brain commits.",
    references: [vrRevisitedReference],
  },
  {
    id: "vr-recovery-and-state-transfer",
    kind: "command",
    topic: "Viewstamped Replication",
    prompt: "Replica R3 restarts after a crash and has lost volatile state. It chooses a fresh nonce and broadcasts RECOVERY in a group of 3 replicas with f = 1. One backup replies, but no reply from the current primary has arrived. May R3 resume normal protocol participation?",
    choices: [
      "Wait for matching-nonce replies from two replicas including the primary, install the primary's protocol/log state, then enter normal status",
      "Resume after any one reply because a recovering replica does not need a quorum",
      "Resume immediately and use PREPARE messages to reconstruct both its view and client table",
      "Run a view change by itself because losing volatile state proves the primary also failed",
    ],
    correctChoice: "Wait for matching-nonce replies from two replicas including the primary, install the primary's protocol/log state, then enter normal status",
    answer: "While recovering, R3 does not participate in normal processing or view changes. It waits for a quorum of f + 1 = 2 RECOVERYRESPONSE messages for its nonce, including the current primary's response with the current view-number, log, op-number, and commit-number. R3 installs that protocol/log state and changes to normal; the nonce prevents stale responses from an older recovery attempt. If R3 also needs application checkpoint state, the optimized protocol obtains it through a separate state transfer before recovery, and that transfer need not come from the primary. A normal backup can likewise use state transfer to repair a detected log gap; neither path makes application state part of RECOVERYRESPONSE.",
    references: [vrRevisitedReference],
  },
  {
    id: "vr-raft-narrow-comparison",
    kind: "command",
    topic: "Viewstamped Replication",
    prompt: "Which is the safest narrow mapping between VR Revisited and Raft? Treat this as recognition vocabulary, not a claim that their state machines or proof rules are identical.",
    choices: [
      "VR view-number and Raft term both identify leadership epochs; VR op-number and Raft log index both position ordered operations, but their election and commit rules remain protocol-specific",
      "VR PREPAREOK is identical to Raft RequestVote, so either message may replace the other",
      "VR commit-number is Raft commitIndex, therefore VR and Raft use the same leader-election and commitment tests",
      "VR primary means Raft candidate, while VR backup means Raft leader",
    ],
    correctChoice: "VR view-number and Raft term both identify leadership epochs; VR op-number and Raft log index both position ordered operations, but their election and commit rules remain protocol-specific",
    answer: "The useful orientation is primary ↔ leader, view-number ↔ term, and op-number ↔ log index. The protocols are not interchangeable: VR's DOVIEWCHANGE log selection is not Raft's RequestVote election restriction, and VR's PREPAREOK-based normal-operation commitment is not Raft's AppendEntries commitment rule. Keep each paper's native messages and invariants when predicting outcomes.",
    references: [vrRevisitedReference, raftReference],
  },
  {
    id: "vr-reconfiguration-epoch-boundary",
    kind: "command",
    topic: "Viewstamped Replication",
    prompt: "An administrator asks VR to replace the old replica group with a new group. The old primary has accepted RECONFIGURATION but it has not committed yet, and the new replicas do not yet have the complete old log. When may the new group begin ordinary client processing?",
    choices: [
      "Commit the RECONFIGURATION as the old epoch's final request; the new group serves clients only after state transfer through that boundary",
      "As soon as any new replica receives STARTEPOCH, even if the old group has not committed RECONFIGURATION",
      "Immediately after the administrator sends RECONFIGURATION, with old and new groups both accepting writes",
      "Only after every old replica has shut down, because state transfer must begin from an empty group",
    ],
    correctChoice: "Commit the RECONFIGURATION as the old epoch's final request; the new group serves clients only after state transfer through that boundary",
    answer: "The old group runs RECONFIGURATION through its normal protocol and makes it the last request of the old epoch. Once it commits, replicas move to the new epoch in transitioning status. The new group may enter normal status and accept clients only after it knows all operations committed in the previous epoch, using state transfer from the old replicas. Old replicas remain available for that transfer until enough new replicas report EPOCHSTARTED; an administrator must not treat commitment alone as completed migration.",
    references: [vrRevisitedReference],
  },
];
